# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EyeTimerWidget_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EyeTimerForm(object):
    def setupUi(self, EyeTimerForm):
        EyeTimerForm.setObjectName("EyeTimerForm")
        EyeTimerForm.resize(755, 382)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EyeTimerForm.sizePolicy().hasHeightForWidth())
        EyeTimerForm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        EyeTimerForm.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(EyeTimerForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(EyeTimerForm)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(EyeTimerForm)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(100)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(EyeTimerForm)
        QtCore.QMetaObject.connectSlotsByName(EyeTimerForm)

    def retranslateUi(self, EyeTimerForm):
        _translate = QtCore.QCoreApplication.translate
        EyeTimerForm.setWindowTitle(_translate("EyeTimerForm", "Позабочусь о твоём зрении"))
        self.pushButton.setText(_translate("EyeTimerForm", "Убрать в трей"))
        self.label.setText(_translate("EyeTimerForm", "00:00"))
