# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReminderWidget_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reminder(object):
    def setupUi(self, Reminder):
        Reminder.setObjectName("Reminder")
        Reminder.resize(361, 280)
        self.verticalLayout = QtWidgets.QVBoxLayout(Reminder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Reminder)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(Reminder)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(Reminder)
        QtCore.QMetaObject.connectSlotsByName(Reminder)

    def retranslateUi(self, Reminder):
        _translate = QtCore.QCoreApplication.translate
        Reminder.setWindowTitle(_translate("Reminder", "Вам пришло напоминание!"))
        self.label.setText(_translate("Reminder", "Напоминаю!"))
